name: Core Doxygen

on:
  push:
    branches: [ master ]

jobs:
  build-doxygen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build the HTML documentation
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          doxyfile-path: ./Doxyfile
          working-directory: ./docs

      # Deploy the HTML documentation to GitHub Pages
      - name: GH Pages Deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: glacial-discharge-downscaling/glacial-discharge-downscaling-doc
          publish_dir: ./docs/html/
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: main
